name: papr_clip_task
description: An app to view short clips

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  # Better value equality
  equatable: ^2.0.3
  # Functional Programming
  dartz: ^0.10.1
  # Network checker
  internet_connection_checker: ^0.0.1+3
  # HTTP Requests
  http: ^0.13.4
  # Business Logic Container
  flutter_bloc: ^8.0.1
  # Service Locator
  get_it: ^7.2.0
  # Icons Library
  font_awesome_flutter: ^9.2.0
  # Responsive expansion
  expandable_text: ^2.2.0
  # Supports youtube links
  youtube_player_flutter: ^8.0.0
  # Spinner and Loaders
  flutter_spinkit: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
